on:
 schedule:
   - cron: "0 2 * * *"

name: Merced weather update

jobs:
  render:
    name: Update graphs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.15' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Retrieve data
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: python scripts/Collect_GHCN_USC00045532_USW00023257.py
          continue_on_error: true
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data
      - name: Build graph
        run:  python scripts/BuildDailyHigh.py
      - name: Commit graph
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update graph
